server:
  port: 8040

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
     user.name: ${spring.security.user.name}
     user.password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
#      defaultZone: http://hlooc:${REGISTRY_SERVER_PASSWORD:admin}@111.231.119.81:8761/eureka/
      defaultZone: http://hlooc:${REGISTRY_SERVER_PASSWORD:admin}@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  main:
    banner-mode: console
  boot:
    admin:
      client:
        url: http://localhost:8040
        username: hlooc
        password: admin
  security:
    user:
      name: hlooc
      password: admin
  profiles:
    active: native


